package com.repository;

public class QuerysRepository {
	
	/*INSERIR UM NOVO ARTISTA*/
	public static final String INSERIR_ARTISTA = "INSERT INTO CAD_ARTISTA(ID_ARTISTA, NOME_ARTISTA) VALUES(?,?)";
 
	/*CONSULTAR TODOS ARTISTAS*/
	public static final String CONSULTAR_ARTISTAS = "SELECT ID_ARTISTA, NOME_ARTISTA FROM CAD_ARTISTA";
 
	/*SELECIONAR UM ARTISTA PELO CÓDIGO*/
	public static final String SELECIONAR_ARTISTA = "SELECT ID_ARTISTA, NOME_ARTISTA FROM CAD_ARTISTA WHERE ID_ARTISTA = :ID_ARTISTA";
 
	/*EXCLUIR UM ARTISTA PELO CÓDIGO*/
	public static final String EXCLUIR_ARTISTA =" DELETE FROM CAD_ARTISTA WHERE ID_ARTISTA = :ID_ARTISTA";
 
	/*ATUALIZAR INFORMAÇÕES DO ARTISTA PELO CÓDIGO*/
	public static final String ATUALIZAR_ARTISTA = "UPDATE CAD_ARTISTA SET NOME_ARTISTA = ? WHERE ID_ARTISTA= ? ";
}
